import "~/styles/globals.css";

import { ClerkProvider } from "@clerk/nextjs";

import { TopNav } from "./_components/topnav";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

export const metadata: Metadata = {
  title: "A tutorial app",
  description: "Generated by someone who loves cats",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${geist.variable} flex flex-col gap-4`}>
        <TopNav/>
        <body>{children}</body>
      </html>
    </ClerkProvider>
  );
}
